package controller;

public enum Commands {

	C_SPANISH, C_ENGLISH, SHOW_ESTADISTIC, SHOW_HOME, SHOW_PLANTLIBRARY, SHOW_LOGIN, SHOW_MOBILE, SHOW_ADDPLANT,
	SHOW_HOMEMOBILE, CLOSE_MOBILE, SHOW_HISTORICALCONTRIBUTIONS, SHOW_TABLEPLANT, 
	SHOW_CREATEBOTANICO,SAVE_BOTANIC,SHOW_TABLE_INSTITUCION, FILTER_SPECIES,SHOW_CREATE_PLANT,SHOW_CHANGEPLANT,SAVE_JSON
	,SHOWMULTI,LOG_IN, SEARCHBY_WORD, SHOW_STATI_INSTI, SHOW_STAT_BY_YEAR,
	SHOW_STAT_BY_BOTANIC,SAVEXML,SHOW_INFOPLANT_MONILE,SHOW_USER_MOBILE,SHOW_CONFI_MOBILE,SHOW_INFO_MOBILE,
	DELETE_BOTANIC,ADD_COUNTRY, ADDPLANTNEW, DELETE_BOTANIC_BUTONPRINCIPAL,FIND_COUNTRY,FIND_SUITABLE,FIND_BY_FAMILY
	,CREATE_PLANT_MOBILE,ADD_COUNTRY_MOBILE,SAVE_JSON_INSTITUTION,SAVEXMLINSTITUTION,SHOW_STAT_BY_FAMILY,SHOW_STATIC_AVALIBLE;

}
